import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/widgets/header/Header";
import Footer from "@/widgets/footer/Footer";

const inter = Inter({
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Cargo X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <link
          rel="shortcut icon"
          href="https://play-lh.googleusercontent.com/deIid8B-gffCIqVd3S0TxIXSzH9DrCcwJO-FmwwJNyPrVNZR0ufL0dv9JZt7N3PKWeI"
          type="image/x-icon"
        />
      </head>
      <html lang="en">
        <body className={`${inter.className}`}>
          <div className="layout">
            <Header />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    </>
  );
}
