import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import Header from "@/widgets/header/Header";
import Footer from "@/widgets/footer/Footer";
import ReactQueryProviders from "./providers/ReactQueryProviders";

const inter = Inter({
  subsets: ["latin", "latin-ext"],
});

export const metadata: Metadata = {
  title: "Cargo X",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <head>
        <link
          rel="shortcut icon"
          href="https://play-lh.googleusercontent.com/deIid8B-gffCIqVd3S0TxIXSzH9DrCcwJO-FmwwJNyPrVNZR0ufL0dv9JZt7N3PKWeI"
          type="image/x-icon"
        />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:100,200,300,regular,500,600,700,800,900,100italic,200italic,300italic,italic,500italic,600italic,700italic,800italic,900italic"
          rel="stylesheet"
        />
      </head>
      <html lang="en">
        <body className={`${inter.className}`}>
          <ReactQueryProviders>
            <div className="layout">
              <Header />
              {children}
              <Footer />
            </div>
          </ReactQueryProviders>
        </body>
      </html>
    </>
  );
}
